#!/usr/bin/env bash
# install and setup nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee file /var/www/html/index.html
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
