#!/usr/bin/env bash
# install and setup nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
sudo sed -i "/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
