#!/usr/bin/env bash
# configures a brand new Ubuntu machine
sudo apt-get update
sudo apt-get -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
