#!/usr/bin/env bash
# configures a brand new Ubuntu machine
sudo apt-get update
sudo apt-get -y nginx
header="\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "31i\ $header" /etc/nginx/sites-enabled/default
sudo service nginx restart
