#!/usr/bin/env bash
# configures a brand new Ubuntu machine

sudo apt update
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
