#!/usr/bin/env bash
# service (init) must say that nginx is not running
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm -r /run/nginx.pid
