#!/usr/bin/env bash
# Bash script that Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely I hate the kill command when receiving a SIGTERM signal Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

terminator() {
  rm /var/run/holbertonscript.pid
  exit
}

echo "$$" > /var/run/holbertonscript.pid

for ((;;))
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'terminator' SIGQUIT

done
