#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
# And print it Ordered from the greatest to the lowest number of occurrences

 awk '{ print $1 " " $9 }'  apache-access.log | sort | uniq -c | sort -rn
